### ISSUE TITLE
Investigating the JoystickButtonMessageDialog.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#11]
Some of these classes in the old code we do not understand what they really are doing. The JoystickButtonDialog class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by ahearnkyle** [comment]
This class seems to only have on functionality of opening a dialog and then closing. It will create a dialog that asks you to press a button, but does nothing with the button press. The only button press that it is looking for is when a "Nevermind" button is pressed and it will simply close the dialog.

**Comment by GashMcNash** [comment]
I checked, it is a very non-essential class.
