### ISSUE TITLE
Investigate the PresetList.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#14]
Some of these classes in the old code we do not understand what they really are doing. The PresetList class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by JDampCoder** [comment]
This class is the preset tab in the lower left of the gui. For presets of certain settings(tilt, rotation, etc.).
Uses a cell renderer for rendering/generating the cells/updating cells for the "table". 
Extends a scrollPane to make the list scrollable.
Each JPanel created is used basically for the columns to display their own data.
setOpaque to make sure the background doesn't change (determines if transparent).
Link to  understand ViewPort: https://www2.htw-dresden.de/~beck/JAVA11/SWING/scrolling.html

Will add more info if needed.

**Comment by JDampCoder** [comment]
The stuff that also controls the presets is in the main GimbalControllerGUI.java that sets the presets and retrieves them as well.

getSelectedIndex retrieves the items in the current list of presets. This is used a lot in the GimbalControllerGUI file to handle the data of that preset.
