### ISSUE TITLE
Investigate the StatusIndicator.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#15]
Some of these classes in the old code we do not understand what they really are doing. The StatusIndicator class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by JDampCoder** [comment]
The status Indicator is the circle icons next to the indicators/color key  of the pan and tilt angles. 
It tells the color of the circle for the moving, soft limit, timeout, etc. 
They are used in the GimbalControllerGui.java file in the upper right section of the main GUI.
This class just sets the color of that circle icon and draws the circle icon.
This is a class that is not as important as the other ones. 
So i would create this as low priority when re-coding in python.

More will be added if more info is requested.
