### ISSUE TITLE
Correctly installing/configuring supplied Gimbal controller software

### ISSUE THREAD

**Issue by GashMcNash** [ahearnkyle/GimbalProject#2]
We need to figure out how to install the already supplied controller software supplied by Mr. Rice and create appropriate documentation for correctly installing it. Issue may reside with the main OS the installer is meant for as the batch file uses linux commands.

**Comment by ahearnkyle** [comment]
I was able to create the java project and Jalen was able to execute the program the successfully. Jalen was able to use the code to actually move the gimbal.

**Comment by JDampCoder** [comment]
I didn't run the java project that was created. I just had to install something and move files in the right place. i'll put more details in a wiki instead. Next time when commenting, using the @username will mention their name as it will help finding certain things/giving credit. (I think)
