### ISSUE TITLE
Infestigate What the AngleControl.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#5]
Some of these classes in the old code we do not understand what they really are doing. The Angle Control class should be investigate so that we know what the exact function of the class is.

**Comment by GashMcNash** [comment]
It appears that this files is a simple setup for the GUI and its angle change logic. There are various spinner objects that change the value in a text box above by either .01, .1, 1, 10, or 100. After the value is changed, it is stored in a angleTextField element. 
It does appear to be helpful for what we are doing as it is only changing values inside the given elements and only listening for changes to said elements. I would not be too concerned with this file outside of checking how finite angle changes are.

**Comment by ahearnkyle** [comment]
This class might be useful when we are going to create the webpage, but I agree with the comment above.
