### ISSUE TITLE
Infestigate What AngleDisplayPanel.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#6]
Some of these classes in the old code we do not understand what they really are doing. The AngleDisplayPanel class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by GashMcNash** [comment]
From what I can see from this class, it is drawing the coordinate system at the bottom of the gui and the logic for drawing on that coordinate system. But it also specifies upper and lower limits called hard and soft limits. Angles drawn on the system all calculated to be within the limits. It is hard to tell what it does without seeing it in action. But I do believe that this code could be considered for reference in determining limits and ranges for the operation of the gimbal.

**Comment by ahearnkyle** [comment]
Can you determine or tell us what the hard and soft limit are? What is their functionality to the gimbals?

**Comment by GashMcNash** [comment]
The the definition of hard and soft limits is that hard limits can never be exceeded as this code assigns explicit values for the hard limits of -90 deg to 90 deg. The soft limits can be set by the user and can be changed. They both dictate how far the gimbal is allowed to. These angles are oriented based on the coordinate system and actually draws out the limits. That is why seeing it in action would be nice.

**Comment by ahearnkyle** [comment]
alright sounds good.
