### ISSUE TITLE
Investigate the EventQueueProxy.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#7]
Some of these classes in the old code we do not understand what they really are doing. The EventQueueProxy class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by GashMcNash** [comment]
This class very simply outputs exceptions and errors to a message box that pops up. Nothing too useful here.

**Comment by ahearnkyle** [comment]
can confirm
